### ISSUE TITLE
preg_match() error after upgrading to 0.5.0

### ISSUE THREAD

**Issue by dan-farley** [soloterm/solo#88]
I upgraded to 0.5.0 and now I'm running into issues when I try to run the "php artisan solo" command.  I downgraded to 0.4.0 and that works correctly, but once I upgraded back to 0.5.0 the issue came back.  Any ideas?

```
% php artisan solo                                               

   ErrorException 

  preg_match(): Compilation failed: unknown property name after \P or \p at offset 22

  at vendor/soloterm/grapheme/src/Grapheme.php:79
     75▕             return static::$cache[$grapheme] = 1;
     76▕         }
     77▕ 
     78▕         // Check for special flag sequence patterns (Scotland, England, etc.)
  ➜  79▕         if (preg_match(static::$flagSequencePattern, $grapheme)) {
     80▕             return static::$cache[$grapheme] = 2;
     81▕         }
     82▕ 
     83▕         // Devanagari conjuncts and other complex scripts

      +26 vendor frames 

  27  artisan:13
      Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
```

**Comment by Patapoof** [comment]
Hi Aaron, thanks for checking! 

Unless I'm wrong, you haven't made a new release, right? I did a composer remove, then readded it and, apart from the requirement changing from "^0.5.0" to "*", I still get soloterm/solo v0.5.0 from march of last year.
